# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditDetails():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editDetails(self):
    self.driver.get("http://1addressbook/")
    self.driver.set_window_size(1175, 629)
    self.driver.find_element(By.NAME, "user").send_keys("admin")
    self.driver.find_element(By.NAME, "pass").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
    self.driver.find_element(By.NAME, "searchform").click()
    self.driver.find_element(By.CSS_SELECTOR, "td.center:nth-child(8) > a:nth-child(1) > img:nth-child(1)").click()
    self.driver.find_element(By.NAME, "middlename").click()
    self.driver.find_element(By.NAME, "firstname").click()
    self.driver.find_element(By.NAME, "firstname").send_keys("b")
    self.driver.find_element(By.NAME, "middlename").click()
    self.driver.find_element(By.NAME, "middlename").send_keys("b")
    self.driver.find_element(By.NAME, "lastname").click()
    self.driver.find_element(By.NAME, "lastname").send_keys("b")
    self.driver.find_element(By.NAME, "nickname").click()
    self.driver.find_element(By.NAME, "nickname").send_keys("b")
    self.driver.find_element(By.NAME, "company").click()
    self.driver.find_element(By.NAME, "company").send_keys("b")
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("b")
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "address").send_keys("b")
    self.driver.find_element(By.NAME, "home").click()
    self.driver.find_element(By.NAME, "home").send_keys("b")
    self.driver.find_element(By.NAME, "mobile").click()
    self.driver.find_element(By.NAME, "mobile").send_keys("b")
    self.driver.find_element(By.NAME, "work").click() #
    self.driver.find_element(By.NAME, "work").send_keys("b")
    self.driver.find_element(By.NAME, "fax").click()
    self.driver.find_element(By.NAME, "fax").send_keys("b")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("b")
    self.driver.find_element(By.NAME, "email2").click()
    self.driver.find_element(By.NAME, "email2").send_keys("b")
    self.driver.find_element(By.NAME, "email3").click()
    self.driver.find_element(By.NAME, "email3").send_keys("b")
    self.driver.find_element(By.NAME, "homepage").click()
    self.driver.find_element(By.NAME, "homepage").send_keys("b")
    self.driver.find_element(By.NAME, "address2").click()
    self.driver.find_element(By.NAME, "address2").send_keys("b")
    self.driver.find_element(By.NAME, "phone2").click()
    self.driver.find_element(By.NAME, "phone2").send_keys("b")
    self.driver.find_element(By.NAME, "notes").click()
    self.driver.find_element(By.NAME, "notes").send_keys("b")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(86)").click()
    self.driver.find_element(By.NAME, "searchstring").send_keys("b")
    ##$##
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()