# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReportTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_reportTest(self):
    self.driver.get("http://sqgs/login.php")
    self.driver.set_window_size(1550, 830)
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".card-body").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Report").click()
    self.driver.find_element(By.ID, "select2-class_id-container").click()
    self.driver.find_element(By.XPATH, '//*/span/ul/li[contains(text(),"Science 7 - C")]').click()
    self.driver.find_element(By.ID, "select2-quarter-container").click()
    self.driver.find_element(By.XPATH, '//*/span/ul/li[contains(text(),"Second")]').click()
    self.driver.find_element(By.ID, "filter").click()
    self.driver.find_element(By.ID, "transmuted_table").click()
    self.driver.find_element(By.ID, "dropdownMenuButton1").click()
    ##$##
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
