# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddUser():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addUser(self):
    self.driver.get("http://savsoftquiz/")
    self.driver.set_window_size(976, 703)
    self.driver.find_element(By.NAME, "username").send_keys("admin")
    self.driver.find_element(By.NAME, "password").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".panel-primary .panel-footer").click()
    self.driver.find_element(By.LINK_TEXT, "Add new").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("test")
    self.driver.find_element(By.NAME, "first_name").send_keys("test")
    self.driver.find_element(By.NAME, "last_name").send_keys("test")
    self.driver.find_element(By.NAME, "user_email").send_keys("test")
    self.driver.find_element(By.NAME, "user_password").send_keys("test")
    self.driver.find_element(By.NAME, "confirm_password").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Users").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-toggle").click()
    ##$##
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.close()
  
