# Generated by Selenium IDE
import pytest
import time
import json
import random
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.select import Select

class TestAddEmp():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addEmp(self):
    self.driver.get("http://ee/admin/login.php")
    self.driver.set_window_size(1550, 830)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123")
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Enrollees").click()
    self.driver.find_element(By.ID, "create_new").click()
    self.driver.find_element(By.ID, "reference_code").click()
    self.driver.find_element(By.ID, "reference_code").send_keys('Emcode'+str(random.randint(100,10000000000)))
    self.driver.find_element(By.ID, "firstname").click()
    self.driver.find_element(By.ID, "firstname").send_keys('Fname'+str(random.randint(100,10000000000)))
    self.driver.find_element(By.ID, "lastname").click()
    self.driver.find_element(By.ID, "lastname").send_keys('Lname'+str(random.randint(100,10000000000)))
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys(str(random.randint(100,10000000000))+'@test.com')
    self.driver.find_element(By.ID, "contact").click()
    self.driver.find_element(By.ID, "contact").send_keys('Contact'+str(random.randint(100,10000000000)))
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys('Address'+str(random.randint(100,10000000000)))
    sel=self.driver.find_element(By.ID, "course_id")
    Select(sel).select_by_index(2)
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mid-large .btn-secondary").click()
    self.driver.find_element(By.ID, "dropdownMenuButton1").click()
    ##$##
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
